DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
        USERID INTEGER NOT NULL,
        FIRSTNAME VARCHAR(35) NOT NULL,
        LASTNAME VARCHAR(35) NOT NULL,
        MIDDLENAME VARCHAR(35) NULL DEFAULT NULL,
        USERNAME VARCHAR(35) NOT NULL,
        PASSWORD VARCHAR(250) NOT NULL,
        EMAILADDRESS VARCHAR(50) NOT NULL,
        PHONENUMBER INTEGER NULL DEFAULT NULL,
        ADDRESS1 VARCHAR(35) NOT NULL,
        ADDRESS2 VARCHAR(35) DEFAULT NULL,
        CITY VARCHAR(25) NOT NULL,
        STATE_PROV VARCHAR(2) NOT NULL,
        ZIP_POST VARCHAR(10) NOT NULL,
        COUNTRY VARCHAR(3) NOT NULL,
        FREQUENTFLYERNUMBER INTEGER NULL DEFAULT NULL,
        D_HOTELS_ID VARCHAR(10) NULL DEFAULT NULL,
        ALAN_RESORTS_ID VARCHAR(10) NULL DEFAULT NULL,
        AGE INTEGER NULL DEFAULT NULL,
        LOYALTYLEVEL VARCHAR(10) NULL DEFAULT NULL,
        PRIMARY KEY (USERID)
);

CREATE TABLE ROLE (
        ROLEID INTEGER NOT NULL,
        USERID INTEGER NOT NULL,
        ROLENAME VARCHAR(25) NOT NULL,
        PRIMARY KEY(ROLEID)
);

ALTER TABLE ROLE ADD FOREIGN KEY (USERID) REFERENCES USER (USERID) ON DELETE CASCADE;

INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (1, 'William', 'Howard', '', 'kylin', 'jboss', 'whow@globochem.com', 2147483647, 'Ap #665-939 Iaculis Road', null, 'Pembroke', 'NC', '48719', 'USA', 733790836, null, null, 18, 'None');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (2, 'Sterling', 'Archer', 'M', 'duchess', 'jboss', 'imawesome@isis.gov', 2147483647, 'Ap #197-361 Quis, St.', null, 'New York', 'NY', '28017', 'USA', 453883790, 'XY32612', null, 19, 'Silver');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (3, 'Kara', 'Thrace', '', 'starbuck', 'jboss', 'starbuck@galactica.com', 2147483647, 'P.O. Box 601, 6936 Nulla. Avenue', null, 'Caprica City', 'DC', '51101', 'USA', 141252654, null, 'QZRT1262', 20, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (4, 'Buffy', 'Summers', '', 'chosen1', 'jboss', 'theslayer@sunnydale.org', 2147483647, '622-6400 Ac Rd.', null, 'Sunnydale', 'CA', '44195', 'USA', 743177622, null, null, 21, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (5, 'Henry', 'Venture', 'Allen', 'hankinator', 'jboss', 'hankinator@venture.com', 2147483647, 'Ap #958-968 Sollicitudin Rd.', null, 'Falls Church', 'MI', '14090', 'USA', 765360316, 'XY161512', 'QZRT1645', 23, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (6, 'Byron', 'Orpheus', '', 'doctor_o', 'jboss', 'dr_o@necromancy.org', 2147483647, '751-3994 Phasellus Road', null, 'Port Arthur', 'IL', '60905', 'USA', 318901745, null, 'QZRT7623', 56, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (7, 'Malcolm', 'Reynolds', '', 'capt_mal', 'jboss', 'browncoat@serenity.com', 2147483647, 'Ap #279-6041 Cursus St.', null, 'El Paso', 'TN', '35325', 'USA', 890397493, null, null, 43, 'Silver');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (8, 'Lana', 'Kane', '', 'yyyup', 'jboss', 'yyyup@isis.gov', 2147483647, '778-5301 Vel St.', null, 'Salem', 'TX', '79883', 'USA', 723175779, null, null, 16, 'None');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (9, 'Peter', 'Lafleur', '', 'avg_joe', 'jboss', 'peter@avgjoe.com', 2147483647, '9638 Nibh. Rd.', null, 'Springfield', 'SC', '60634', 'USA', 160896801, null, null, 38, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (10, 'Cyril', 'Figgus', '', 'stirfryday', 'jboss', 'comptrol@isis.gov', 2147483647, 'Ap #552-454 Sagittis. Rd.', null, 'Dubuque', 'NE', '86987', 'USA', 273724890, null, null, 44, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (11, 'Motoko', 'Kusanagi', '', 'the_major', 'jboss', 'major@section9.org', 2147483647, '6108 Sed Av.', null, 'Layton', 'WV', '79742', 'USA', 531722590, null, null, 20, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (12, 'Chloe', 'Sullivan', 'Elizabeth', 'watchtower', 'jboss', 'watchtower@jla.org', 2147483647, 'Ap #571-372 Facilisis Ave', null, 'Metropolis', 'KA', '77002', 'USA', 409787762, null, null, 49, 'None');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (13, 'Hunter', 'Gathers', '', 'goodintel', 'jboss', 'gathers@osi.gov', 2147483647, 'P.O. Box 803, 3482 Tortor, St.', null, 'Benton Harbor', 'WV', '24975', 'USA', 671710421, null, null, 37, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (14, 'Hal', 'Jordan', '', 'lantern', 'jboss', 'gl@jla.org', 2147483647, 'Ap #303-6363 Nec St.', null, 'Agoura Hills', 'MS', '71975', 'USA', 665821336, null, null, 44, 'Silver');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (15, 'Edward', 'Elrich', '', 'fullmetal', 'jboss', 'fullmetal@alchemy.org', 2147483647, 'P.O. Box 574, 2495 In Ave', null, 'Bowie', 'MS', '53677', 'USA', 190152924, null, null, 76, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (16, 'Sheldon', 'Cooper', 'L', 'iq187', 'jboss', 'moonpie@caltech.edu', 2147483647, '1792 Nisi Street', null, 'Williston', 'TX', '86543', 'USA', 567956309, null, null, 17, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (17, 'Tony', 'Stark', '', 'ironman', 'jboss', 'stark@starkindustries.com', 2147483647, 'Ap #239-4239 Massa St.', null, 'San Fernando', 'NH', '99199', 'USA', 973715422, null, null, 87, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (18, 'Conway', 'Stern', '', 'smooth', 'jboss', 'smooth@isis.gov', 2147483647, 'P.O. Box 237, 6408 In Ave', null, 'Milwaukee', 'KS', '15172', 'USA', 163332504, null, null, 14, 'Gold');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (19, 'Beatrix', 'Kiddo', '', 'bride', 'jboss', 'blackmamba@viper.com', 2147483647, '8823 Vel, Street', null, 'Lubbock', 'NV', '14784', 'USA', 875873496, null, null, 32, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (20, 'Jay', 'Boss', 'A.', 'student', 'jboss', 'student@jbtraining.com', 2147483647, 'P.O. BOX 13588', null, 'Raleigh', 'NC', '27713', 'USA', 123456789, null, null, 21, 'Bronze');
INSERT INTO USER(USERID, FIRSTNAME, LASTNAME, MIDDLENAME, USERNAME, PASSWORD, EMAILADDRESS, PHONENUMBER, ADDRESS1, ADDRESS2, CITY, STATE_PROV, ZIP_POST, COUNTRY, FREQUENTFLYERNUMBER, D_HOTELS_ID, ALAN_RESORTS_ID, AGE, LOYALTYLEVEL) VALUES (21, 'admin', 'admin', '', 'admin', 'admin', 'admin@jbtraining.com', 2147483647, 'P.O. BOX 13588', null, 'Raleigh', 'NC', '27713', 'USA', 123456789, null, null, 99, 'Gold');

INSERT INTO ROLE(ROLEID, USERID, ROLENAME) VALUES(1, 1, 'PAYLVL1');
INSERT INTO ROLE(ROLEID, USERID, ROLENAME) VALUES(2, 2, 'PAYLVL2');
