package org.wildfly.tutorial.persistence.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="ROLE")
public class Role {
	@Id
	@Column(columnDefinition="INT")
	private int roleid;

	@Basic
	@Column(nullable=false, length=25)
	private String rolename;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="USERID", columnDefinition="INT", nullable=false)
	private User user;


	public Role() {
	}

	public Role(int roleid) {
		this.roleid = roleid;
	}

	public int getRoleid() {
		return roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}