package org.wildfly.tutorial.persistence.entity;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="USER")
public class User {
	@Basic
	@Column(nullable=false, length=35)
	private String address1;

	@Basic
	@Column(length=35)
	private String address2;

	@Basic
	@Column(columnDefinition="INT")
	private int age;

	@Basic
	@Column(name="ALAN_RESORTS_ID", length=10)
	private String alanResortsId;

	@Basic
	@Column(nullable=false, length=25)
	private String city;

	@Basic
	@Column(nullable=false, length=3)
	private String country;

	@Basic
	@Column(name="D_HOTELS_ID", length=10)
	private String dHotelsId;

	@Basic
	@Column(nullable=false, length=50)
	private String emailaddress;

	@Basic
	@Column(nullable=false, length=35)
	private String firstname;

	@Basic
	@Column(columnDefinition="INT")
	private int frequentflyernumber;

	@Basic
	@Column(nullable=false, length=35)
	private String lastname;

	@Basic
	@Column(length=10)
	private String loyaltylevel;

	@Basic
	@Column(length=35)
	private String middlename;

	@Basic
	@Column(nullable=false, length=250)
	private String password;

	@Basic
	@Column(columnDefinition="INT")
	private int phonenumber;

	@OneToMany(targetEntity=org.wildfly.tutorial.persistence.entity.Role.class, mappedBy="user", cascade=CascadeType.MERGE)
	private Set roles = new HashSet();

	@Basic
	@Column(name="STATE_PROV", nullable=false, length=2)
	private String stateProv;

	@Id
	@Column(columnDefinition="INT")
	private int userid;

	@Basic
	@Column(nullable=false, length=35)
	private String username;

	@Basic
	@Column(name="ZIP_POST", nullable=false, length=10)
	private String zipPost;


	public User() {
	}

	public User(int userid) {
		this.userid = userid;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getAlanResortsId() {
		return alanResortsId;
	}

	public void setAlanResortsId(String alanResortsId) {
		this.alanResortsId = alanResortsId;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDHotelsId() {
		return dHotelsId;
	}

	public void setDHotelsId(String dHotelsId) {
		this.dHotelsId = dHotelsId;
	}

	public String getEmailaddress() {
		return emailaddress;
	}

	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public int getFrequentflyernumber() {
		return frequentflyernumber;
	}

	public void setFrequentflyernumber(int frequentflyernumber) {
		this.frequentflyernumber = frequentflyernumber;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getLoyaltylevel() {
		return loyaltylevel;
	}

	public void setLoyaltylevel(String loyaltylevel) {
		this.loyaltylevel = loyaltylevel;
	}

	public String getMiddlename() {
		return middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getPhonenumber() {
		return phonenumber;
	}

	public void setPhonenumber(int phonenumber) {
		this.phonenumber = phonenumber;
	}

	public Set getRoles() {
		return roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public String getStateProv() {
		return stateProv;
	}

	public void setStateProv(String stateProv) {
		this.stateProv = stateProv;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getZipPost() {
		return zipPost;
	}

	public void setZipPost(String zipPost) {
		this.zipPost = zipPost;
	}
}